### ISSUE TITLE
US East VM Mcbeth

### ISSUE THREAD

**Issue by GrayEye** [pennsignals/sre#9]
Set up a new VM in Us East for Rafe to use. See if the nfs loses significant speed being in a different data center.

**Comment by GrayEye** [comment]
UPHS doesn't have any virtual network setup for US East. Any machine created in that region is inaccessible.

**Comment by GrayEye** [comment]
Close this ticket, we cannot do this in US East

**Comment by jlubken** [comment]
I got quota in useast 2, so that other regions are not needed.
